### ISSUE TITLE
Последовательность init-boot

### ISSUE THREAD

**Issue by dannuclear** [OpenIPC/burn#22]
Две камеры: gk7205v200. Обе отвечают по uart.
В скрипт burn добавил вывод последовательности для доступа к boot
` def init_bootmode(self):`
      `  i = 0`
    `    counter = 0`
    `    while i < 30:`
     `       in_bin = self.s.read(1)`
     `       print(in_bin) <-- Вот этот вывод`

Вывод первой камеры:
![изображение](https://github.com/OpenIPC/burn/assets/54681550/a1b4a330-eec8-427b-9b4c-421e553d8d29)
Все ок!

Вывод второй камеры:
![изображение](https://github.com/OpenIPC/burn/assets/54681550/d5429792-9ecc-4a03-a761-843d1c9f39d5)

Последовательность камера не выдает и соответственно не загружает в память образ. Встречалась ли ранее такая проблема?

**Comment by widgetii** [comment]
Проверьте работу проблемной камеры на оригинальном софте вендора (GkTool)

**Comment by dannuclear** [comment]
Причина ясна, приношу извинения, чип v500
