### ISSUE TITLE
Unlock gk7205v200

### ISSUE THREAD

**Issue by advorkovyy** [OpenIPC/burn#7]
Is there special image to unlock gk7205v200?

Want to make full firmware backup before loading OpenIPC on it, but the bootloader is password-protected.

**Comment by widgetii** [comment]
You can use [our own gk7205v200 U-Boot](https://github.com/OpenIPC/firmware/releases/download/latest/u-boot-gk7205v200-universal.bin)

**Comment by advorkovyy** [comment]
Will I be able to revert to original firmware once I burn this bootloader?

I have a module with zoom and af motors, not quite sure if things work out with OpenIPC. Want to have a possibility to go back if needed.

This is what I worry about:

Back up your original firmware!
Our version of U-Boot, once installed, overwrites original crypto partition, making it impossible to revert to the original factory firmware unless you have a full flash backup for a specific camera!

**Comment by widgetii** [comment]
You don't need to burn it into flash to use it, despite the name of the program, it loads and runs U-Boot in DRAM. If I understood right, you just need a tool to make a full flash image backup of original firmware and this do the job.

If you use Coupler then to migrate to OpenIPC it will change only Linux and rootfs partition, everything else will be stayed original (U-boot, env, and crypto)

**Comment by advorkovyy** [comment]
Thanks! Name indeed confusing. I thought it will burn (write) another bootloader into flash.

It seems that Coupler does not support my module: I think it is not from XM. I have full admin console via web interface and firmware version is V23.1.11.16.3-20220524. There is no branding besides IP Camera. https://www.aliexpress.com/item/32827040443.html

So I use `burn` to load universal bootloader into DRAM, this will allow me to make the full flash backup. And then I just follow instructions on https://openipc.org/cameras/vendors/goke/socs/gk7205v200 , right?

**Comment by widgetii** [comment]
Right, if you have full backup for your SoC it's possible to restore everything

Judging by screenshots, your module is CamHi. Probably, this code will work for PTZ module https://github.com/OpenIPC/motors/tree/master/camhi-motor

**Comment by advorkovyy** [comment]
Thanks a lot! My original issue is resolved: I was able to create a backup, then flash OpenIPC. 

I have ssh, WebUI working, but Majestic will require tweaking to get right.
